SELECT ?uri ?countlabel ?samplelabel
WHERE {
{
SELECT ?uri (COUNT (?xlabel) AS ?countlabel) (SAMPLE(?xlabel) AS ?samplelabel)
WHERE {
?uri a ufVivo:UFEntity .
?uri a foaf:Organization .
?uri rdfs:label ?xlabel .
}
GROUP BY ?uri
}
FILTER (?countlabel >1)
}